### ISSUE TITLE
Fourth template

### ISSUE THREAD

**Issue by djluckett** [TarHeelBiostatistics/TarHeelTexSlides#1]
Let's add the fourth template.

that would be cool!! 🎆 😸 🚀

**Comment by phoebejiang** [comment]
Crystal, do it

**Comment by BarkleyBG** [comment]
@cttnguyen 👀

**Comment by BarkleyBG** [comment]
@cttnguyen, when you add the template, [add text in your commit message that will automatically close this issue when pushing the commit](https://help.github.com/articles/closing-issues-via-commit-messages/).


Thanks!
