### ISSUE TITLE
Beamer source code not included in this file

### ISSUE THREAD

**Issue by shaina-alexandria** [TarHeelBiostatistics/TarHeelTexSlides#4]
I'm trying to use this template without having previously used Beamer, and I am getting the error 

```
"! LaTeX Error: File `beamer.cls' not found". 
```

Can we provide this beamer.cls file here, or could users be pointed to where it can be found?

**Comment by BarkleyBG** [comment]
It seems that you're encountering a similar problem to the one [shown here on SO](https://tex.stackexchange.com/questions/163918/beamer-cls-error-how-to-install-beamer), is that correct?
(explicit URL: https://tex.stackexchange.com/questions/163918/beamer-cls-error-how-to-install-beamer)

Perhaps you can change your miktex to install the beamer package,[ as shown in this SO post](https://tex.stackexchange.com/questions/111125/latex-packages-automatic-versus-manual-installation-and-related-issues)?
(explicit URL: https://tex.stackexchange.com/questions/111125/latex-packages-automatic-versus-manual-installation-and-related-issues)

Alternatively, it looks like[ this GH Repo ](https://github.com/josephwright/beamer) would be helpful. Perhaps you can download the `beamer.cls` file from there?

**Comment by BarkleyBG** [comment]
Shaina's issue has been solved by knitting an RMarkdown Beamer script. Details:

- open RStudio
- Open an RMarkdown document that creates a Beamer presentation
- attempt to "knit" the RMarkdown document
- R should install the `rmarkdown` package and the things it depends on
   - somewhere in this magic, the root issue was solved and Beamer worked.

So, follow the above steps and this may be solved. If not, please post a new issue. Closing this for now.
